from typing import List, Optional, Protocol

from entity.task import Task


class TaskRepository(Protocol):
    def get_all(self) -> List[Task]: ...
    def get_by_id(self, task_id: int) -> Optional[Task]: ...
    def add(self, task: Task) -> None: ...
    def update(self, task: Task) -> None: ...
    def remove(self, task_id: int) -> None: ...
    def next_id(self) -> int: ...
